export enum LoanType {
  STARTUP = 'STARTUP',
  ENTERPRISE = 'ENTERPRISE',
}

export enum AsteroidType {
  PLANET = 'PLANET',
  MOON = 'MOON',
  ASTEROID = 'ASTEROID',
  GAS_GIANT = 'GAS_GIANT',
}

export enum GoodType {
  CHEMICALS = 'CHEMICALS',
  CONSTRUCTION_MATERIALS = 'CONSTRUCTION_MATERIALS',
  CONSUMER_GOODS = 'CONSUMER_GOODS',
  ELECTRONICS = 'ELECTRONICS',
  FOOD = 'FOOD',
  FUEL = 'FUEL',
  MACHINERY = 'MACHINERY',
  METALS = 'METALS',
  RARE_METALS = 'RARE_METALS',
  RESEARCH = 'RESEARCH',
  SHIP_PARTS = 'SHIP_PARTS',
  SHIP_PLATING = 'SHIP_PLATING',
  TEXTILES = 'TEXTILES',
  DRONES = 'DRONES',
  UNSTABLE_COMPOUNDS = 'UNSTABLE_COMPOUNDS',
  EXOTIC_PLASMA = 'EXOTIC_PLASMA',
  FUSION_REACTORS = 'FUSION_REACTORS',
  PROTEIN_SYNTHESIZERS = 'PROTEIN_SYNTHESIZERS',
  EXPLOSIVES = 'EXPLOSIVES',
  NANOBOTS = 'NANOBOTS',
  BIOMETRIC_FIREARMS = 'BIOMETRIC_FIREARMS',
  PRECISION_INSTRUMENTS = 'PRECISION_INSTRUMENTS',
  NARCOTICS = 'NARCOTICS',
}
