export enum LoanType {
  STARTUP = 'STARTUP',
  ENTERPRISE = 'ENTERPRISE',
}

export enum AsteroidType {
  PLANET = 'PLANET',
  MOON = 'MOON',
  ASTEROID = 'ASTEROID',
  GAS_GIANT = 'GAS_GIANT',
}

export enum GoodType {
  FUEL = 'FUEL',
  METALS = 'METALS',
  WORKERS = 'WORKERS',
  FOOD = 'FOOD',
  RESEARCH = 'RESEARCH',
  CHEMICALS = 'CHEMICALS',
  MACHINERY = 'MACHINERY',
  SHIP_PARTS = 'SHIP_PARTS',
  ELECTRONICS = 'ELECTRONICS',
  RARE_METALS = 'RARE_METALS',
  SHIP_PLATING = 'SHIP_PLATING',
  CONSTRUCTION_MATERIALS = 'CONSTRUCTION_MATERIALS',
  CONSUMER_GOODS = 'CONSUMER_GOODS'
}
